version: '3'

services:
  rails:
    build: .
    image: jacksonpires/ubuntu-rails-ssh
    volumes:
      - .:/projects
    ports:
      - "3000"
      - "22"
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: mypassword
    volumes:
      - ./postgres:/var/lib/postgresql/data
    ports:
      - "5432"
